global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: order_service
    metrics_path: /metrics
    static_configs:
      - targets: ["13.232.214.142"]

  - job_name: inventory_service
    metrics_path: /metrics
    static_configs:
      - targets: ["3.7.71.27"]
