global:
  scrape_interval: 5s

scrape_configs:
  - job_name: Inventory Service
    metrics_path: /inventory/metrics
    static_configs:
      - targets: ["host.docker.internal:4000"]

  - job_name: Order Service
    metrics_path: /orders/metrics
    static_configs:
      - targets: ["host.docker.internal:4000"]
