global:
  scrape_interval: 5s
  
scrape_configs:
  - job_name: Scrape API Service
    static_configs:
      - targets: ['192.168.0.185:5000']

  - job_name: Scrape Message Broker
    static_configs:
      - targets: ['192.168.0.185:6000']