global:
  scrape_interval: 5s
  
scrape_configs:
  - job_name: Inventory Service
    static_configs:
      - targets: ['host.docker.internal:4000']

  - job_name: Order Service
    static_configs:
      - targets: ['host.docker.internal:5000']