global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: order_service
    static_configs:
      - targets: ["192.168.1.7:4001"]

  - job_name: inventory_service
    static_configs:
      - targets: ["192.168.1.7:4002"]
