version: "3.8"
services:

  redis:
    image: redis
    ports:
      - 6379:6379

  inventory:
    image: "inventory-service"
    ports:
      - 4000:4000
    build : "./apps/inventory-service/."
    depends_on:
      - redis

  order:
    image: "order-service"
    ports:
      - "5000:5000"
    build : "./apps/order-service/."
    depends_on:
      - redis
  
