apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prom-server:9090
    isDefault: true

  - name: Loki
    type: loki
    access: loki
    url: http://loki:3100
    isDefault: false
