apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  type: LoadBalancer  # Change from NodePort
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002